package ro.webdata.parser.xml.dc.core.attribute;

import ro.webdata.parser.xml.dc.common.Constants;

public class AttributeValue {
    public static final String EMPTY = Constants.EMPTY_STRING;
    public static final String NONE = "none";

    public static final String ELEMENT_CONTRIBUTOR = "contributor";
    public static final String ELEMENT_COVERAGE = "coverage";
    public static final String ELEMENT_CREATOR = "creator";
    public static final String ELEMENT_DATE = "date";
    public static final String ELEMENT_DESCRIPTION = "description";
    public static final String ELEMENT_FORMAT = "format";
    public static final String ELEMENT_IDENTIFIER = "identifier";
    public static final String ELEMENT_LANGUAGE = "language";
    public static final String ELEMENT_PUBLISHER = "publisher";
    public static final String ELEMENT_RELATION = "relation";
    public static final String ELEMENT_RIGHTS = "rights";
    public static final String ELEMENT_SOURCE = "source";
    public static final String ELEMENT_SUBJECT = "subject";
    public static final String ELEMENT_THUMB = "thumb";
    public static final String ELEMENT_TITLE = "title";
    public static final String ELEMENT_TYPE = "type";

    public static final String QUALIFIER_ABSTRACT = "abstract";
    public static final String QUALIFIER_ACCESSIONED = "accessioned";
    public static final String QUALIFIER_ADVISOR = "advisor";
    public static final String QUALIFIER_ALTERNATIVE = "alternative";
    public static final String QUALIFIER_AUTHOR = "author";
    public static final String QUALIFIER_AVAILABLE = "available";
    public static final String QUALIFIER_CLASSIFICATION = "classification";
    public static final String QUALIFIER_CITATION = "citation";
    public static final String QUALIFIER_COPYRIGHT = "copyright";
    public static final String QUALIFIER_CREATED = "created";
    public static final String QUALIFIER_DDC = "ddc";
    public static final String QUALIFIER_EDITOR = "editor";
    public static final String QUALIFIER_EXTENT = "extent";
    public static final String QUALIFIER_GOV_DOC = "govdoc";
    public static final String QUALIFIER_HAS_PART = "haspart";
    public static final String QUALIFIER_HAS_VERSION = "hasversion";
    public static final String QUALIFIER_HOLDER = "holder";
    public static final String QUALIFIER_ILLUSTRATOR = "illustrator";
    public static final String QUALIFIER_IS_BASED_ON = "isbasedon";
    public static final String QUALIFIER_IS_FORMAT_OF = "isformatof";
    public static final String QUALIFIER_IS_PART_OF = "ispartof";
    public static final String QUALIFIER_IS_PART_OF_SERIES = "ispartofseries";
    public static final String QUALIFIER_IS_REFERENCED_BY = "isreferencedby";
    public static final String QUALIFIER_IS_REPLACED_BY = "isreplacedby";
    public static final String QUALIFIER_IS_VERSION_OF = "isversionof";
    public static final String QUALIFIER_ISBN = "isbn";
    public static final String QUALIFIER_ISMN = "ismn";
    public static final String QUALIFIER_ISSN = "issn";
    public static final String QUALIFIER_ISO = "iso";
    public static final String QUALIFIER_ISSUED = "issued";
    public static final String QUALIFIER_LCC = "lcc";
    public static final String QUALIFIER_LCSH = "lcsh";
    public static final String QUALIFIER_MEDIUM = "medium";
    public static final String QUALIFIER_MESH = "mesh";
    public static final String QUALIFIER_MIME_TYPE = "mimetype";
    public static final String QUALIFIER_OTHER = "other";
    public static final String QUALIFIER_PROVENANCE = "provenance";
    public static final String QUALIFIER_REPLACES = "replaces";
    public static final String QUALIFIER_REQUIRES = "requires";
    public static final String QUALIFIER_RFC_3066 = "rfc3066";
    public static final String QUALIFIER_SICI = "sici";
    public static final String QUALIFIER_SLUG = "slug";
    public static final String QUALIFIER_STATEMENT_OF_RESPONSIBILITY = "statementofresponsibility";
    public static final String QUALIFIER_SPATIAL = "spatial";
    public static final String QUALIFIER_SPONSORSHIP = "sponsorship";
    public static final String QUALIFIER_T100 = "t100";
    public static final String QUALIFIER_TABLE_OF_CONTENTS = "tableofcontents";
    public static final String QUALIFIER_TEMPORAL = "temporal";
    public static final String QUALIFIER_UPDATED = "updated";
    public static final String QUALIFIER_URI = "uri";
    public static final String QUALIFIER_VERSION = "version";
}
